### PR TITLE
gl_preprocess: handle more self-referencing sectors

### LINKED ISSUE #216: OpenGL rendering glitch in Alien Vendetta (av.wad)
A self-referencing sector used to create deep water in MAP01 shows a HOM effect:

doom00

The outer sector (which should be rendered) fails to be tessellated in `gl_preprocess.c` because it is not closed:

```
sector 36 is not closed at vertex 188 ! 10 lines in sector
sector 36 is not closed at vertex 189 ! 10 lines in sector
sector 36 is not closed at vertex 190 ! 10 lines in sector
sector 36 is not closed at vertex 191 ! 10 lines in sector
```

Candidate lines that would close it are actually tagged with the inner self-referencing sector (37), e.g. the highlighted one here:

Screenshot from 2023-02-23 00-09-03

### PR DESCRIPTION
**Pull request by bkoropoff**
When a sector can't be tessellated as a whole because it's not closed, the GL renderer falls back on subsector tesselation. If the sector in question contains self-referencing sectors (used for deep water and other tricks), these won't be tesselated, causing HOM.

Explicitly detect self-referencing sectors and what sector contains them (i.e. what should be rendered in their place), and account for them during subsector tessellation.

Closes #216 

doom00

### CODE REVIEW

File: prboom2/src/gl_preprocess.c [hunk 1]
```diff
@@ -695,6 +706,78 @@ static void gld_PrecalculateSector(int num)
   Z_Free(lineadded);
 }
 
+static dboolean gld_SectorIsSelfReferencing(sector_t* sector)
+{
+  int i;
+
+  for (i = 0; i < sector->linecount; ++i) {
```
Comment (kraflab) [inline prboom2/src/gl_preprocess.c]: I realize it's a bit annoying because the style is different in different files, but please put the `{` below the line here (and in the other cases).

**Comment by kraflab** [comment]
This looks a lot better for sure 😄

File: prboom2/src/gl_preprocess.c [hunk 2]
```diff
@@ -695,6 +706,83 @@ static void gld_PrecalculateSector(int num)
...
+    // We're self-referencing, but we couldn't find another sector across
+    // a self-referencing linedef.  It appears that this can happen due
+    // to the way the node builder generates subsectors, causing
+    // R_PointInSubsector not to find what we're looking for
+    // (e.g. Alien Vendetta MAP01 sector 39). Look for a neighboring
+    // self-referencing sector and point at that instead.
+    for (i = 0; i < sector->linecount; ++i)
+    {
+      line_t* l = sector->lines[i];
+      if (l->sidenum[0] != NO_INDEX &&
```
Comment (kraflab) [inline prboom2/src/gl_preprocess.c]: Can we check `l->frontsector` and `l->backsector` directly?

Comment (bkoropoff) [reply prboom2/src/gl_preprocess.c]: The existing code was not consistent about using it, but yeah, it looks equivalent.

File: prboom2/src/gl_preprocess.c [hunk 3]
```diff
@@ -695,6 +706,83 @@ static void gld_PrecalculateSector(int num)
...
+      if (s1 != NULL && s1 != sector)
+        return s1;
+      if (s2 != NULL && s2 != sector)
+        return s2;
+    }
+  }
+
+  if (selfref)
+  {
+    // We're self-referencing, but we couldn't find another sector across
```
Comment (bkoropoff) [inline prboom2/src/gl_preprocess.c]: I think this part of the logic is susceptible to false positives, so I'm going to rework it

**Comment by bkoropoff** [comment]
I reworked the logic a bit to be more conservative.  It involves a pre-pass to decide which sectors are "real" (i.e. non-self-referencing), but this makes false positives exceptionally unlikely, and simplifies the rest.

**Comment by bkoropoff** [comment]
Now with even more paranoia.

File: prboom2/src/gl_preprocess.c [hunk 4]
```diff
@@ -695,6 +705,163 @@ static void gld_PrecalculateSector(int num)
...
+    if (sector->lines[i]->v1 == line->v1 || sector->lines[i]->v2 == line->v1)
+      v1c++;
+    if (sector->lines[i]->v2 == line->v2 || sector->lines[i]->v2 == line->v2)
+      v2c++;
+  }
+
+  // Line is still real if:
+  // - It's isolated (no neighbors), i.e. it's floating mid-sector
+  // - It has more than 1 neighbor per vertex, i.e. it divides the sector
+  return (v1c == 0 && v2c == 0) || (v1c > 1 && v2c > 1);
```
Comment (kraflab) [inline prboom2/src/gl_preprocess.c]: Should it just be `v1c != 1 && v2c != 1`? I.e., what about a line that has more than one neighbor on one vertex and no neighbors on the other vertex?

File: prboom2/src/gl_preprocess.c [hunk 5]
```diff
@@ -695,6 +705,163 @@ static void gld_PrecalculateSector(int num)
...
+      if (!gld_IsRealLine(&sectors[i], sectors[i].lines[j])) {
+        real = false;
+        break;
+      }
+    }
+    if (real)
+      sectors[i].flags |= SECTOR_IS_REAL;
+  }
+
+  // Now mark all transitively real sectors in passes (to avoid recursive calls)
```
Comment (kraflab) [inline prboom2/src/gl_preprocess.c]: I'm concerned about a loop that may check tens of thousands of sectors repeatedly 😅

**Comment by kraflab** [comment]
Well, I am once again not sure I want to commit this just to fix that bug 😅

File: prboom2/src/gl_preprocess.c (hunk 4 above)
Comment (bkoropoff) [reply prboom2/src/gl_preprocess.c]: Yeah, good point

File: prboom2/src/gl_preprocess.c (hunk 5 above)
Comment (bkoropoff) [reply prboom2/src/gl_preprocess.c]: The vast majority of sectors will be tagged by the first loop, meaning this loop will run at most once or twice in practice.  This does have worst case N^2 runtime, but it would only occur on a map which consists of N sectors chained end-to-end, with the first N-1 being self-referencing.  That's not a very realistic map.

This loop could be removed, but I was trying to be extremely paranoid about treating a sector as self-referencing when it isn't.

Comment (bkoropoff) [reply prboom2/src/gl_preprocess.c]: I'll rework this to use an explicit queue and avoid visiting unnecessary sectors.

**Comment by bkoropoff** [comment]
I think this is fairly straightforward compared to some of the other hacks to support software rendering quirks that are already in the code (and don't actually cover all cases, as I've found...)

**Comment by kraflab** [comment]
Alright, looks great now 👍 
Thanks!
