### PR TITLE
s_sound:raven: use test that's safe on degenmobj_t

### LINKED ISSUE #313: Hexen polyobj sounds cause out-of-bounds access
```
==105931==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x61d000928e78 at pc 0x0000006de371 bp 0x7fff
ffffdd60 sp 0x7fffffffdd58
READ of size 8 at 0x61d000928e78 thread T0
    #0 0x6de370 in Raven_S_getChannel /var/home/bkoropoff/Source/dsda-doom/prboom2/src/s_sound.c:986
    #1 0x6ded0f in Raven_S_StartSoundAtVolume /var/home/bkoropoff/Source/dsda-doom/prboom2/src/s_sound.c:1111
    #2 0x6d9ae0 in S_StartSoundAtVolume /var/home/bkoropoff/Source/dsda-doom/prboom2/src/s_sound.c:290
    #3 0x504279 in SN_UpdateActiveSequences /var/home/bkoropoff/Source/dsda-doom/prboom2/src/hexen/sn_sonix.c:37
4
    #4 0x6db6ab in S_UpdateSounds /var/home/bkoropoff/Source/dsda-doom/prboom2/src/s_sound.c:547
    #5 0x4a7ebf in D_DoomLoop /var/home/bkoropoff/Source/dsda-doom/prboom2/src/d_main.c:557
    #6 0x4acf72 in D_DoomMain /var/home/bkoropoff/Source/dsda-doom/prboom2/src/d_main.c:1910
    #7 0x6fddd4 in main /var/home/bkoropoff/Source/dsda-doom/prboom2/src/SDL/i_main.c:314
    #8 0x7ffff6e2850f in __libc_start_call_main (/lib64/libc.so.6+0x2750f)
    #9 0x7ffff6e285c8 in __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x275c8)
    #10 0x4088b4 in _start (/var/home/bkoropoff/Data/Source/dsda-doom/builddebug/dsda-doom+0x4088b4)

0x61d000928e78 is located 80 bytes to the right of 1960-byte region [0x61d000928680,0x61d000928e28)
allocated by thread T0 here:
    #0 0x7ffff79cb6af in __interceptor_malloc (/lib64/libasan.so.8+0xba6af)
    #1 0x6f8edf in Z_MallocTag /var/home/bkoropoff/Source/dsda-doom/prboom2/src/z_zone.c:98
    #2 0x6f97e2 in Z_MallocLevel /var/home/bkoropoff/Source/dsda-doom/prboom2/src/z_zone.c:217
    #3 0x50287e in PO_Init /var/home/bkoropoff/Source/dsda-doom/prboom2/src/hexen/po_man.c:1483
    #4 0x63c32c in P_SetupLevel /var/home/bkoropoff/Source/dsda-doom/prboom2/src/p_setup.c:3907
    #5 0x4bcca0 in G_DoLoadLevel /var/home/bkoropoff/Source/dsda-doom/prboom2/src/g_game.c:1162
    #6 0x4c758e in G_InitNew /var/home/bkoropoff/Source/dsda-doom/prboom2/src/g_game.c:2982
    #7 0x4acefa in D_DoomMainSetup /var/home/bkoropoff/Source/dsda-doom/prboom2/src/d_main.c:1888
    #8 0x4acf6d in D_DoomMain /var/home/bkoropoff/Source/dsda-doom/prboom2/src/d_main.c:1908
    #9 0x6fddd4 in main /var/home/bkoropoff/Source/dsda-doom/prboom2/src/SDL/i_main.c:314
    #10 0x7ffff6e2850f in __libc_start_call_main (/lib64/libc.so.6+0x2750f)
```

Fault occurred here:

```c
    if (gamestate != GS_LEVEL || origin->player)
```

`origin` is within allocated memory, but `origin->player` is not.  This appears to be because poly objects use a dummy `mobj_t` structure which is too short, so the memory access is wild:

```c
// Each sector has a degenmobj_t in its center for sound origin purposes.
typedef struct
{
  thinker_t thinker;  // not used for anything
  fixed_t x, y, z;
} degenmobj_t;

...

typedef struct polyobj_s
{
  ...
  degenmobj_t startSpot;
  ...
}
```

### PR DESCRIPTION
**Pull request by bkoropoff**
Closes #313

### CODE REVIEW

File: prboom2/src/s_sound.c [hunk 1]
```diff
@@ -983,7 +983,7 @@ static int Raven_S_getChannel(mobj_t *origin, sfxinfo_t *sfx, sfx_params_t *para
 
   for (i = 0; i < numChannels; i++)
   {
-    if (gamestate != GS_LEVEL || origin->player)
+    if (gamestate != GS_LEVEL || origin == players[displayplayer].mo)
```
Comment (kraflab) [inline prboom2/src/s_sound.c:986]: This changes player sound behaviour in coop demos, but it probably doesn't make much difference in practice. Rewriting this file to not use ambiguous pointers is on my list, but for now this should be fine.

**Comment by kraflab** [comment]
Thanks for the catch
