### PR TITLE
Switch to libxmp for tracker music

### LINKED ISSUE #719: Tracker music doesn't loop correctly
I'll make a PR for this.

Report 1:

> Just found a bug with IT module playback
> In 0.29.2, when the IT module music in this map is finished playing (about 9 minutes in), it does not loop back to the start and the playback just stops right there. In 0.29.0 the music loops back to the start normally after reaching the end.
> Haven't tested this with other IT files or other tracker module formats
> https://www.doomworld.com/idgames/levels/doom2/Ports/p-r/portglacia

Report 2:

> dsda has some trouble playing the music on NoSp3 MAP19
> fails to loop
> https://www.doomworld.com/idgames/levels/doom2/Ports/megawads/nosp3

Xaser's comment:

> the module itself is being naughty, unfortunately -- it uses a global volume fade at the end of the track, but doesn't set it back to max volume at the beginning, so after fading it out stays at zero volume after the loop

Xaser's examples:

> the music suite for dead-wire works as a sub-song test-case -- basically check if the first ambient subtrack still loops [mad-labs.zip](https://github.com/user-attachments/files/21208228/mad-labs.zip)
> 
> here's an example of one that seemingly doesn't loop, because it fades out the global volume and doesn't reset it (i.e. the common oopsie) [fusionfaktor.zip](https://github.com/user-attachments/files/21208230/fusionfaktor.zip)

All of the above in one wad: [tracker_songs.zip](https://github.com/user-attachments/files/21208236/tracker_songs.zip)
```
Name       Time        Source
D_RUNNIN   0:09:12.94  PORTGLACIA.wad MAP01 D_RUNNIN
D_STALKS   0:05:53.98  mad-labs.it
D_COUNTD   0:04:43.41  fusionfaktor.it
D_BETWEEE  0:03:04.30  NoSp3.wad MAP19 D_SHAWN2
```

### PR DESCRIPTION
**Pull request by ceski-1**
Fixes https://github.com/kraflab/dsda-doom/issues/719
Alternative to https://github.com/kraflab/dsda-doom/pull/720

### CODE REVIEW

File: prboom2/src/MUSIC/xmpplayer.c [hunk 1]
```diff
@@ -0,0 +1,188 @@
...
+{
+  if (xmp_playing && !xmp_paused)
+  {
+    if (xmp_play_buffer(context, dest, nsamp * 4, xmp_looping ? 0 : 1) == 0)
+    {
+      short *sdest = (short *)dest;
+
+      for (int i = 0; i < nsamp * 2; i++)
+      {
+        sdest[i] = (short)(sdest[i] * xmp_volume);
```
Comment (rfomin) [inline prboom2/src/MUSIC/xmpplayer.c:150]: We can use the  [xmp_set_player](https://xmp.sourceforge.net/libxmp.html#int-xmp-set-player-xmp-context-c-int-param-int-val) function with the `XMP_PLAYER_VOLUME` master volume parameter.

**Review by rfomin — COMMENTED** [review]
Thank you!

File: prboom2/src/MUSIC/xmpplayer.c (hunk 1 above)
Comment (ceski-1) [reply prboom2/src/MUSIC/xmpplayer.c:150]: That's the first method I tried and it didn't work correctly. It seems like the song can adjust that value whenever it wants.

Comment (rfomin) [reply prboom2/src/MUSIC/xmpplayer.c:150]: Okay, I understand.

**Review by rfomin — APPROVED** [review]

File: prboom2/vcpkg.json
Comment (FtZPetruska) [inline prboom2/vcpkg.json:1]: Just a minor nitpick: `vcpkg format-manifest prboom2/vcpkg.json` should be run on the manifest.

Comment (ceski-1) [reply prboom2/vcpkg.json:1]: Fixed, thanks.

**Comment by ceski-1** [comment]
Okay, this is ready to go (use squash merge).

**Comment by axunes** [comment]
I would like to ask if the removal of the library is necessary. libxmp is great but it's missing some of the module formats' features (fm support for scream tracker 3 modules, amiga resampler) as well as loads of quality-of-life features (known as MPT hacks) from libopenmpt (accurate configurable tempo, dsp effects, song- and instrument-defined interpolation modes, and a bunch of extra commands to make up for limitations within the original formats)

a lot of that may sound like fluff, but along with configurable interpolation, the accurate tempo mode in particular is sorely missed, it allows for a configurable tick rate for smoother pitch slides and such, where normally you are limited to historical frame-based timings for computers with wavetable mixing hardware, which gives even less precision than doom's original MUS format. with software mixing that is not a concern, so it would be nice to have the option of libopenmpt which is not only designed to accurately play modules of the time but also add features necessary to accommodate the modules being created today

**Comment by elf-alchemist** [comment]
The main concern with using libxmp is cross-port consistency. If you look at many modern, actively developed ports, Crispy (via SDL_Mixer), Woof, DSDA, U/GZDoom (via ZMusic), Helion (also via ZMusic) are all using using libxmp under the hood, this is by design, there are many fundamental glaring differences between tracker implementations due to the lack of proper format standardization, which is incredibly lacking compared to MIDI, for example. This is highly problematic as every port can and will sound different from each other, and we will receive independent but fundamentally related bug reports for said inconsistent behavior everywhere. As such it is far easier for us to use the same library across the board _and_ send issues to said single library, so we will all receive the same updates from upstream, it would be far more costly, in both time and effort to submit these kinds of separate reports to multiple upstream libraries separately and independently, or even worse trying to make patches within the source ports using multiple workarounds. In short it is much simpler and less burdenous for port devs and composers alike to share the same support, it just makes our lives easier.

Related, but there have already been reports made to libxmp to add support for openmpt extensions, as per one U/GZDoom contributor noticing that Graf Zahl updated ZMusic to play tracker with OMPT extensions with libDUMB instead of sending a fix/report upstream. Similarly, a libopenmpt compat issue had also been reported as well:

https://github.com/libxmp/libxmp/issues/885

https://github.com/libxmp/libxmp/issues/886

If you can, I would also ask that you contribute your feature requests to their GitHub issues as well, unreported issues are forever untackled, after all.
